#!/usr/bin/env bash
# Installs nginx on local machine
# Makes configurational changes to NginX on local machine

apt-get update -y && apt-get upgrade -y
apt-get install nginx -y
chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
