#!/usr/bin/env bash
# Installs NginX
# Edit the nginx congiguration files
# Redirects to youtube on redirect_me

apt-get update -y
apt-get upgrade -y
apt-get install nginx -y
chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "26i $line" /etc/nginx/sites-available/default
service nginx restart
