#!/usr/bin/env bash
# A Bash script that:
# 1. Creates the file /var/run/myscript.pid containing its PID
# 2. Displays To infinity and beyond indefinitely
# 3. Displays I hate the kill command when receiving a SIGTERM signal
# 4. Displays Y U no love me?! when receiving a SIGINT signal
# 5. Deletes the file /var/run/myscript.pid and terminates
#	itself when receiving a SIGQUIT or SIGTERM signal

echo "$$" > /var/run/myscript.pid

trap 'echo Y U no love me?!' SIGINT
trap 'rm /var/run/myscript.pid && pkill $$' SIGQUIT
trap 'echo I hate the kill command && rm /var/run/myscript.pid && pkill $$' SIGTERM

while true; do
	echo "To infinity and beyond"
done
